version: "3.7"
services:
  material-requests:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:13"
    restart: always
    ports:
      - 5432:54320
    environment:
      POSTGRES_DB: requests
      POSTGRES_PASSWORD: my_password

